### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '<pesonal_path>/PDS_Project/data/output/mannheim_transformed.csv'

### ISSUE THREAD

**Issue by LHumpe** [phipag/PDS_Project#4]
please Add a check if output folder exists if not call os.makedir for the ooutput folder in method save of transformer to prevent this issue

**Comment by phipag** [comment]
Thanks for the bug report. I will look into it.

**Comment by phipag** [comment]
Fixed by 0e26a630
